application:
  subdomain: linuxcommandlibrary
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://linuxcommandlibrary:8080/
services:
  linuxcommandlibrary:
    # upstream: czyt/linux-command-library:v0.1.3
    image: registry.lazycat.cloud/czyt/czyt/linux-command-library:918795fd40b46164
    environment:
      - DATABASE_PATH=/app/database.db
      - SERVER_ADDR=0.0.0.0:8080
      - ENABLE_CORS=true
      - RUST_LOG=info
